version: 2
jobs:
  # TODO: Should this be a test and build?
  test:
    docker:
      - image: circleci/node:12.22.5
    working_directory: ~/arcads
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
